version: "3.8"
services:
  app:
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    command: npm run dev
